databases:
  - name: aira-db
    plan: free

services:
  - type: web
    name: aira-attendance
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app --bind 0.0.0.0:$PORT --workers 1 --threads 4 --timeout 120"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: FACE_DET_SIZE
        value: "320"  
      - key: FACE_MODEL
        value: buffalo_s
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: DATABASE_URL
        fromDatabase:
          name: aira-db
          property: connectionString
